---
- name: "PLAY1 PRINT OUT HOSTNAME, GROUPNAME and OS for IOS"
  hosts: eve
  gather_facts: false

  tasks:
#    - name: "TASK1 : PRINT DEBUG MAGIC VARIABLES FOR IOS"
#      ansible.builtin.debug:
#        msg: >-
#          The hostname is {{ inventory_hostname }} and the group name is {{ group_names }}
#          and the OS is {{ ansible_network_os }}
#    - name: "TASK2 : SENDING SHOW COMMAND TO DEVICE"
#      cisco.ios.ios_command:
#        commands: show version
#    - name: "TASK3 : SENDING MULTIPLESHOW COMMAND TO DEVICE"
#      cisco.ios.ios_command:
#        commands:
#          - show version
#          - show ip int brief
#          - dir
#
#    - name: "TASK4 - RUN AND PARSE COMMAND WITH NTC TEMPLATE"
#      ansible.utils.cli_parse:
#        command: "show ip interface brief"
#        parser:
#          name: "ansible.netcommon.ntc_templates"
#        set_fact: "interfaces_ntc"
#    - name: "TASK5 - PRINT DEBUG NTC PARSED OUTPUT"
#      ansible.builtin.debug:
#        msg: "{{ ansible_facts['interfaces_ntc'] }}"
#    - name: "TASK6 - PRINT DEBUG NTC PARSED OUTPUT FOR FIRST INTERFACE"
#      ansible.builtin.debug:
#        msg: "{{ ansible_facts['interfaces_ntc'][0] }}"
#    - name: "TASK7 PRINT OUTPUT REGISTERED FROM SHOW COMMAND"
#      cisco.ios.ios_command:
#        commands:
#          - show ip interface brief
#          - show version
#      register: show_command_output
#    - name: "TASK8 PRINT OUTPUT REGISTERED FROM SHOW COMMAND"
#     ansible.builtin.debug:
#        msg: "{{ show_command_output }}"
#    - name: "TASK9 CREATE OUTPUT DIR IF IT DOES NOT EXIST"
#      ansible.builtin.file:
#        path: "show_outputs"
#        state: directory
#        mode: "0755"
#      run_once: true
#    - name: "TASK11 EXTRACT VLANS FROM SHOW COMMAND OUTPUT"
#      cisco.ios.ios_vlans:
#        state: gathered
#      register: vlan_output
#   - name: "TASK12 PRINT DEBUG VLAN OUTPUT"
#      ansible.builtin.debug:
#        var: vlan_output.gathered
#
#    - name: "TASK10 WRITE J2 TEMPLATE TO FORMAT AND SAVE OUTPUT"
#      ansible.builtin.template:
#        src: "templates/show_command.j2"
#        dest: "show_outputs/{{ inventory_hostname }}_show_command.txt"
#       mode: "0644"
#    - name: "TASK13 GATHER IOS DEVICE FACT AND STORE IT INTO MEMORY"
#      cisco.ios.ios_facts:
#        gather_subset:
#          - "all"
#      register: raw_facts
#    - name: "TASK14 TAKE FACTS INTO MEMORY AND SEND THEM TO A J2 TEMPLATE"
#      ansible.builtin.debug:
#        var: raw_facts
#    - name: "TASK15 TAKE FACTS INTO MEMORY AND SEND THEM TO A J2 TEMPLATE"
#      ansible.builtin.copy:
#        content: "{{ lookup('template', 'facts_template.j2') }}"
#        dest: "show_outputs/{{ inventory_hostname }}_facts.txt"
#        mode: "0644"
#   - name: "TASK16 TAKE FACTS INTO MEMORY AND SEND THEM TO A J2 TEMPLATE"
#      ansible.builtin.debug:
#        msg: raw_facts
#    - name: "TASK17 CONFIGURE CDP AND LLDP ON THE DEVICE"
#      cisco.ios.ios_config:
#        lines:
#          - "cdp run"
#          - "lldp run"
#    - name: "TASK18 CONFIGURE A LOOPBACK WITH A VARIABLE"
#      cisco.ios.ios_config:
#        lines:
#          - description "This is a loopback interface"
#          - ip address {{ loopback_ip }} {{ loopback_mask }}
 #       parents:
  #        - interface Loopback1230
#    - name: "TASK19 EXTRACT VARIABLES FROM HOST_VARS AND GROUP_VARS"
#      ansible.builtin.template:
#        src: "templates/host_vars_template.j2"
#        dest: "show_outputs/{{ inventory_hostname }}_host_vars.txt"
#        mode: "0644"
#    - name: "TASK20 BUILD AND PUSH SNMP CONFIGURATION TO DEVICE"
#      ansible.builtin.template:
#        src: "templates/snmp.j2"
#        dest: "show_outputs/{{ inventory_hostname }}_snmp.txt"
#        mode: "0644"
#    - name: "TASK21 BUILD AND PUSH SNMP CONFIGURATION TO DEVICE"
#      ansible.builtin.cli_config:
#        config: "{{ lookup('template', 'templates/snmp.j2') }}"
#    - name: "TASK22 VERIFYSNMP CONFIGURATION TO DEVICE"
#      ansible.builtin.cli_command:
#        command: "show run | include {{ snmp.get('RO') }}"
     - name: "TASK23  CONFIGURATION OF VLAN INTERFACE TO  DEVICE"
       ansible.builtin.template:
        src: "templates/ios_template.j2"
        dest: "show_outputs/{{ inventory_hostname }}_ios.txt"
        mode: "0644"
     - name: "TASK24  CONFIGURATION OF VLAN INTERFACE TO  DEVICE"
       cisco.ios.ios_config:
        diff_against: running
        src: "show_outputs/{{ inventory_hostname }}_ios.txt"
        backup: yes
        save_when: modified
#        diff_ignore_lines:
#          - "! Last configuration change.*"

     - name: "TASK25  VERIFY OF VLAN INTERFACE TO  DEVICE"
       cisco.ios.ios_command:
        commands:
          - show ip interface brief 
       register: output 
     - name: "TASK26  DISPLAY OF VLAN INTERFACE TO  DEVICE"
       ansible.builtin.debug:
        msg: "{{ output.stdout_lines }}"
