---
- name: My Playbook
  hosts: eve
  gather_facts: false

  tasks:
    - name: "PRINT DEBUG MAGIC VARIABLES FOR IOS"
      ansible.builtin.debug:
        msg: "The hostname is {{ inventory_hostname }} and the group name is {{ group_names }} and the OS is {{ ansible_network_os }}"
